services:
  kc-postgresql:
    image: postgres:16
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 2s
      retries: 300
    env_file:
      - .env
      - env.d/kc_postgresql
    volumes:
      - ./data/databases/keycloak:/var/lib/postgresql/data/pgdata
    networks:
      - default

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    restart: always
    command: ["start", "--import-realm"]
    env_file:
      - .env
      - env.d/kc_postgresql
      - env.d/keycloak
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_HOST}`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls.certresolver=letsencrypt"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    volumes:
      - ../docker/auth/realm.json:/opt/keycloak/data/import/realm.json
      - ../docker/keycloak/themes/aiobi:/opt/keycloak/themes/aiobi
    depends_on:
      kc-postgresql:
        condition: service_healthy
        restart: true
    networks:
      - aiobi-public
      - default
      - prod-app

networks:
  aiobi-public:
    external: true
  prod-app:
    name: prod-app
  default:
