# Generated by Django 5.2.12 on 2026-04-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_room_scheduled_date_room_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_tier',
            field=models.CharField(choices=[('normal', 'Normal'), ('enterprise', 'Enterprise')], default='normal', help_text='Subscription tier. Enterprise users have access to recording and transcription.', max_length=20, verbose_name='account tier'),
        ),
        migrations.AlterField(
            model_name='room',
            name='configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Values for Aïobi Meet parameters to configure the room.', verbose_name='Aïobi Meet room configuration'),
        ),
    ]
