# Generated by Django 5.2.12 on 2026-04-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_account_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='transcription_deletion_scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When set, the transcription will be automatically deleted at this datetime. Used to give users a 48h warning before deletion when the storage limit is reached.', null=True, verbose_name='Transcription deletion scheduled at'),
        ),
    ]
