# Generated by Django 5.2.12 on 2026-04-07 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_recording_transcription_deletion_scheduled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('livekit_room_sid', models.CharField(blank=True, max_length=255, null=True, verbose_name='LiveKit room SID')),
                ('started_at', models.DateTimeField(verbose_name='Started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended at')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room session',
                'verbose_name_plural': 'Room sessions',
                'db_table': 'meet_room_session',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('livekit_identity', models.CharField(max_length=255, verbose_name='LiveKit identity')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Display name')),
                ('joined_at', models.DateTimeField(verbose_name='Joined at')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Left at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_participations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.roomsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Room participant',
                'verbose_name_plural': 'Room participants',
                'db_table': 'meet_room_participant',
                'ordering': ('joined_at',),
                'constraints': [models.UniqueConstraint(fields=('session', 'livekit_identity'), name='unique_participant_per_session')],
            },
        ),
    ]
