# Generated by Django 5.2.12 on 2026-04-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_roomsession_roomparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsession',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
