# Generated by Django 5.2.12 on 2026-04-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_roomsession_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='invited_emails',
            field=models.JSONField(blank=True, default=list, verbose_name='Invited emails'),
        ),
    ]
