# Generated by Django 5.2.12 on 2026-04-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_room_invited_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tier_upgraded_notified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last time the user was notified by email of an enterprise tier upgrade. Used to prevent duplicate welcome emails if the tier is re-synced.', null=True, verbose_name='tier upgrade notified at'),
        ),
    ]
